In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('../../data/preprocessed_data.csv')
data.head(5)

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0 -0.110249  -0.007679  -0.004919       -0.089486 -0.007736 -0.095076   
1 -0.110249  -0.007737  -0.004919       -0.089486 -0.007736 -0.095076   
2 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3 -0.110249  -0.007723  -0.002891       -0.089486 -0.007736 -0.095076   
4 -0.110249  -0.007728  -0.004814       -0.089486 -0.007736 -0.095076   

   num_failed_logins  num_compromised  su_attempted  num_root  ...  \
0          -0.027023        -0.011664     -0.024437 -0.012385  ...   
1          -0.027023        -0.011664     -0.024437 -0.012385  ...   
2          -0.027023        -0.011664     -0.024437 -0.012385  ...   
3          -0.027023        -0.011664     -0.024437 -0.012385  ...   
4          -0.027023        -0.011664     -0.024437 -0.012385  ...   

   service_smtp  flag_S0  flag_SF  flag_other  land_1  logged_in_1  \
0             0        0        1           0       0            0   
1             0        0        1           0       0            0   
2             0        1        0           0       0            0   
3             0        0        1           0       0            1   
4             0        0        1           0       0            1   

   root_shell_1  is_host_login_1  is_guest_login_1  attack_category  
0             0                0                 0                1  
1             0                0                 0                1  
2             0                0                 0                0  
3             0                0                 0                1  
4             0                0                 0                1  

[5 rows x 47 columns]

In [3]:
X = data.drop(['attack_category'],axis=1)
y = data['attack_category']

In [4]:
X.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'num_compromised', 'su_attempted', 'num_root',
       'num_file_creations', 'num_shells', 'num_access_files', 'count',
       'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
       'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate',
       'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'protocol_type_tcp',
       'protocol_type_udp', 'service_http', 'service_other', 'service_private',
       'service_smtp', 'flag_S0', 'flag_SF', 'flag_other', 'land_1',
       'logged_in_1', 'root_shell_1', 'is_host_login_1', 'is_guest_login_1'],
      dtype='object')

<br/>
<br/>
<br/>

### TRAIN TEST SPLIT

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size = 0.3 , random_state = 42 , stratify = y )

In [6]:
X_train.shape , X_test.shape

((88181, 46), (37792, 46))

In [7]:
y_train.shape , y_test.shape

((88181,), (37792,))

<br/>
<br/>

#### REINDEXING DATAFRAME

In [8]:
X_train = X_train.reset_index( drop = True )
y_train = y_train.reset_index( drop = True )

X_test = X_test.reset_index( drop = True )
y_test = y_test.reset_index( drop = True )

In [9]:
X_train

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
1     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
2     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
4     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
...         ...        ...        ...             ...       ...       ...   
88176 -0.110249  -0.007727  -0.004514       -0.089486 -0.007736 -0.095076   
88177 -0.110249  -0.007755  -0.004887       -0.089486 -0.007736 -0.095076   
88178 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
88179 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
88180 -0.110249  -0.007755  -0.004908       -0.089486 -0.007736 -0.095076   

       num_failed_logins  num_compromised  su_attempted  num_root  ...  \
0              -0.027023        -0.011664     -0.024437 -0.012385  ...   
1              -0.027023        -0.011664     -0.024437 -0.012385  ...   
2              -0.027023        -0.011664     -0.024437 -0.012385  ...   
3              -0.027023        -0.011664     -0.024437 -0.012385  ...   
4              -0.027023        -0.011664     -0.024437 -0.012385  ...   
...                  ...              ...           ...       ...  ...   
88176          -0.027023        -0.011664     -0.024437 -0.012385  ...   
88177          -0.027023        -0.011664     -0.024437 -0.012385  ...   
88178          -0.027023        -0.011664     -0.024437 -0.012385  ...   
88179          -0.027023        -0.011664     -0.024437 -0.012385  ...   
88180          -0.027023        -0.011664     -0.024437 -0.012385  ...   

       service_private  service_smtp  flag_S0  flag_SF  flag_other  land_1  \
0                    0             0        1        0           0       0   
1                    0             0        0        0           0       0   
2                    0             0        1        0           0       0   
3                    0             0        1        0           0       0   
4                    1             0        0        1           0       0   
...                ...           ...      ...      ...         ...     ...   
88176                0             0        0        1           0       0   
88177                0             0        0        1           0       0   
88178                1             0        1        0           0       0   
88179                0             0        0        0           0       0   
88180                0             0        0        1           0       0   

       logged_in_1  root_shell_1  is_host_login_1  is_guest_login_1  
0                0             0                0                 0  
1                0             0                0                 0  
2                0             0                0                 0  
3                0             0                0                 0  
4                0             0                0                 0  
...            ...           ...              ...               ...  
88176            1             0                0                 0  
88177            0             0                0                 0  
88178            0             0                0                 0  
88179            0             0                0                 0  
88180            0             0                0                 0  

[88181 rows x 46 columns]

In [10]:
X_test

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
1     -0.110249  -0.007707  -0.004843       -0.089486 -0.007736 -0.095076   
2     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
4     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
...         ...        ...        ...             ...       ...       ...   
37787 -0.110249  -0.007741  -0.004919       -0.089486 -0.007736 -0.095076   
37788 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
37789 -0.110249  -0.007709  -0.004393       -0.089486 -0.007736 -0.095076   
37790 -0.110249  -0.007722  -0.001621       -0.089486 -0.007736 -0.095076   
37791 -0.110249  -0.007478  -0.004837       -0.089486 -0.007736 -0.095076   

       num_failed_logins  num_compromised  su_attempted  num_root  ...  \
0              -0.027023        -0.011664     -0.024437 -0.012385  ...   
1              -0.027023        -0.011664     -0.024437 -0.012385  ...   
2              -0.027023        -0.011664     -0.024437 -0.012385  ...   
3              -0.027023        -0.011664     -0.024437 -0.012385  ...   
4              -0.027023        -0.011664     -0.024437 -0.012385  ...   
...                  ...              ...           ...       ...  ...   
37787          -0.027023        -0.011664     -0.024437 -0.012385  ...   
37788          -0.027023        -0.011664     -0.024437 -0.012385  ...   
37789          -0.027023        -0.011664     -0.024437 -0.012385  ...   
37790          -0.027023        -0.011664     -0.024437 -0.012385  ...   
37791          -0.027023        -0.011664     -0.024437 -0.012385  ...   

       service_private  service_smtp  flag_S0  flag_SF  flag_other  land_1  \
0                    0             0        0        0           1       0   
1                    0             0        0        1           0       0   
2                    1             0        0        0           0       0   
3                    0             0        1        0           0       0   
4                    1             0        0        0           0       0   
...                ...           ...      ...      ...         ...     ...   
37787                0             0        0        1           0       0   
37788                1             0        1        0           0       0   
37789                0             0        0        1           0       0   
37790                0             0        0        1           0       0   
37791                0             1        0        1           0       0   

       logged_in_1  root_shell_1  is_host_login_1  is_guest_login_1  
0                0             0                0                 0  
1                1             0                0                 0  
2                0             0                0                 0  
3                0             0                0                 0  
4                0             0                0                 0  
...            ...           ...              ...               ...  
37787            0             0                0                 0  
37788            0             0                0                 0  
37789            1             0                0                 0  
37790            1             0                0                 0  
37791            1             0                0                 0  

[37792 rows x 46 columns]

<br/>
<br/>
<br/>

### MODEL

In [14]:
from sklearn.naive_bayes import GaussianNB , BernoulliNB

gnb = GaussianNB()
bnb = BernoulliNB()

In [12]:
gnb.fit(X_train,y_train)
y_pred_gnb = gnb.predict(X_test)

In [15]:
bnb.fit(X_train,y_train)
y_pred_bnb = bnb.predict(X_test)

In [17]:
from sklearn.metrics import classification_report
y_true = y_test
target_names = [ 'dos', 'normal', 'probe' , 'r2l' , 'u2r' ]

print("=====================GAUSSIAN NAIVE BAYES====================")
report = classification_report(y_true, y_pred_gnb, target_names=target_names)
print(report)

=====================GAUSSIAN NAIVE BAYES====================
              precision    recall  f1-score   support

         dos       0.60      0.95      0.73     13778
      normal       0.91      0.15      0.26     20479
       probe       0.47      0.97      0.63      3497
         r2l       0.01      0.88      0.01        25
         u2r       0.01      0.92      0.02        13

    accuracy                           0.52     37792
   macro avg       0.40      0.77      0.33     37792
weighted avg       0.76      0.52      0.46     37792



In [23]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_true,y_pred_gnb)
pd.DataFrame(conf_mat , index = target_names , columns = target_names)

dos  normal  probe   r2l   u2r
dos     13026     287    462     0     3
normal   8752    3069   3360  4169  1129
probe      29       7   3386     5    70
r2l         2       0      0    22     1
u2r         0       0      0     1    12

In [19]:
print("================BERNOULLI NAIVE BAYES================")
report = classification_report(y_true, y_pred_bnb, target_names=target_names)
print(report)

================MULTINOMIAL NAIVE BAYES================
              precision    recall  f1-score   support

         dos       0.98      0.75      0.85     13778
      normal       0.89      0.91      0.90     20479
       probe       0.32      0.57      0.41      3497
         r2l       0.24      0.64      0.35        25
         u2r       0.14      0.77      0.23        13

    accuracy                           0.82     37792
   macro avg       0.52      0.73      0.55     37792
weighted avg       0.87      0.82      0.84     37792



In [24]:
conf_mat = confusion_matrix( y_true , y_pred_bnb )
pd.DataFrame(conf_mat , index = target_names , columns = target_names)

dos  normal  probe  r2l  u2r
dos     10358     891   2515   14    0
normal     71   18690   1623   34   61
probe     137    1373   1984    2    1
r2l         2       6      0   16    1
u2r         0       3      0    0   10

<br/>
<br/>
<br/>

#### SAVING DATA FOR GAUSSIAN NAIVE BAYES

In [25]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score 

accuracy = accuracy_score(y_true, y_pred_gnb)
precision = precision_score( y_true , y_pred_gnb , average = None )
recall = recall_score( y_true , y_pred_gnb , average = None )
f1score = f1_score( y_true , y_pred_gnb , average = None )

print(accuracy)
print(precision)
print(recall)
print(f1score)

0.5163791278577476
[0.59727635 0.91257806 0.46975583 0.00524184 0.00987654]
[0.94542024 0.14986083 0.96825851 0.88       0.92307692]
[0.73206508 0.25744485 0.63260159 0.0104216  0.01954397]


In [27]:
data = {
    "model" : "Gaussian Naive Bayes",
    "accuracy" : accuracy ,
    "precision" : precision.tolist() ,
    "recall" : recall.tolist() ,
    "F1_score" : f1score.tolist() ,
    "class_names" : target_names
}

data

{'model': 'Gaussian Naive Bayes',
 'accuracy': 0.5163791278577476,
 'precision': [0.5972763537988903,
  0.9125780553077609,
  0.4697558268590455,
  0.005241839409101739,
  0.009876543209876543],
 'recall': [0.9454202351574975,
  0.14986083304848868,
  0.9682585072919645,
  0.88,
  0.9230769230769231],
 'F1_score': [0.7320650799449236,
  0.2574448452311047,
  0.6326015880429706,
  0.010421601136901942,
  0.01954397394136808],
 'class_names': ['dos', 'normal', 'probe', 'r2l', 'u2r']}

In [28]:
import json
with open("../../model_performances/gaussian_naive_bayes.json", "w") as outfile:
    json.dump(data, outfile)

<br/>
<br/>
<br/>

#### SAVING DATA FOR BERNOULLI NAIVE BAYES

In [29]:
accuracy = accuracy_score(y_true, y_pred_bnb)
precision = precision_score( y_true , y_pred_bnb , average = None )
recall = recall_score( y_true , y_pred_bnb , average = None )
f1score = f1_score( y_true , y_pred_bnb , average = None )

print(accuracy)
print(precision)
print(recall)
print(f1score)

0.8218141405588484
[0.98012869 0.89157086 0.3240771  0.24242424 0.1369863 ]
[0.7517782  0.91264222 0.56734344 0.64       0.76923077]
[0.85089953 0.9019835  0.41251689 0.35164835 0.23255814]


In [30]:
data = {
    "model" : "Bernoulli Naive Bayes",
    "accuracy" : accuracy ,
    "precision" : precision.tolist() ,
    "recall" : recall.tolist() ,
    "F1_score" : f1score.tolist() ,
    "class_names" : target_names
}

data

{'model': 'Bernoulli Naive Bayes',
 'accuracy': 0.8218141405588484,
 'precision': [0.9801286903860712,
  0.8915708629490053,
  0.32407709898725906,
  0.24242424242424243,
  0.136986301369863],
 'recall': [0.7517781971258528,
  0.9126422188583427,
  0.567343437231913,
  0.64,
  0.7692307692307693],
 'F1_score': [0.8508995317505956,
  0.9019834950050674,
  0.4125168936479884,
  0.3516483516483516,
  0.23255813953488372],
 'class_names': ['dos', 'normal', 'probe', 'r2l', 'u2r']}

In [31]:
import json
with open("../../model_performances/bernoulli_naive_bayes.json", "w") as outfile:
    json.dump(data, outfile)