In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
pd.set_option('display.max_columns', 50)
df = pd.read_csv('../../data/preprocessed_data.csv')

In [3]:
df.head()

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0 -0.110249  -0.007679  -0.004919       -0.089486 -0.007736 -0.095076   
1 -0.110249  -0.007737  -0.004919       -0.089486 -0.007736 -0.095076   
2 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3 -0.110249  -0.007723  -0.002891       -0.089486 -0.007736 -0.095076   
4 -0.110249  -0.007728  -0.004814       -0.089486 -0.007736 -0.095076   

   num_failed_logins  num_compromised  su_attempted  num_root  \
0          -0.027023        -0.011664     -0.024437 -0.012385   
1          -0.027023        -0.011664     -0.024437 -0.012385   
2          -0.027023        -0.011664     -0.024437 -0.012385   
3          -0.027023        -0.011664     -0.024437 -0.012385   
4          -0.027023        -0.011664     -0.024437 -0.012385   

   num_file_creations  num_shells  num_access_files     count  srv_count  \
0            -0.02618    -0.01861         -0.041221 -0.717045  -0.354343   
1            -0.02618    -0.01861         -0.041221 -0.620982  -0.368110   
2            -0.02618    -0.01861         -0.041221  0.339648  -0.299273   
3            -0.02618    -0.01861         -0.041221 -0.690846  -0.313041   
4            -0.02618    -0.01861         -0.041221 -0.472521   0.058678   

   serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  same_srv_rate  \
0    -0.637209        -0.631929    -0.374362        -0.374432       0.771283   
1    -0.637209        -0.631929    -0.374362        -0.374432      -1.321428   
2     1.602664         1.605104    -0.374362        -0.374432      -1.389669   
3    -0.189235        -0.184522    -0.374362        -0.374432       0.771283   
4    -0.637209        -0.631929    -0.374362        -0.374432       0.771283   

   diff_srv_rate  srv_diff_host_rate  dst_host_count  dst_host_srv_count  \
0      -0.349683           -0.374560       -0.324063           -0.818890   
1       0.482201           -0.374560        0.734343           -1.035688   
2       0.038529           -0.374560        0.734343           -0.809857   
3      -0.349683           -0.374560       -1.533670            1.258754   
4      -0.349683           -0.028179        0.734343            1.258754   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0               -0.782367               -0.280282   
1               -1.161030                2.736852   
2               -0.938287               -0.174417   
3                1.066401               -0.439078   
4                1.066401               -0.439078   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                     0.069972                    -0.289103   
1                     2.367737                    -0.289103   
2                    -0.480197                    -0.289103   
3                    -0.383108                     0.066252   
4                    -0.480197                    -0.289103   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0             -0.639532                 -0.624871             -0.224532   
1             -0.639532                 -0.624871             -0.387635   
2              1.608759                  1.618955             -0.387635   
3             -0.572083                 -0.602433             -0.387635   
4             -0.639532                 -0.624871             -0.387635   

   dst_host_srv_rerror_rate  protocol_type_tcp  protocol_type_udp  \
0                 -0.376387                  1                  0   
1                 -0.376387                  0                  1   
2                 -0.376387                  1                  0   
3                 -0.345084                  1                  0   
4                 -0.376387                  1                  0   

   service_http  service_other  service_private  service_smtp  flag_S0  \
0             0              0                0             0        0   
1             0              1                0             0     

In [4]:
df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'num_compromised', 'su_attempted', 'num_root',
       'num_file_creations', 'num_shells', 'num_access_files', 'count',
       'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
       'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate',
       'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'protocol_type_tcp',
       'protocol_type_udp', 'service_http', 'service_other', 'service_private',
       'service_smtp', 'flag_S0', 'flag_SF', 'flag_other', 'land_1',
       'logged_in_1', 'root_shell_1', 'is_host_login_1', 'is_guest_login_1',
       'attack_category'],
      dtype='object')

<br/>
<br/>

#### TRAIN TEST SPLIT

In [7]:
from sklearn.model_selection import train_test_split

X = df.drop(['attack_category'],axis=1)
y = df['attack_category']

X_train,X_test,y_train,y_test = train_test_split( X , y , test_size=0.3 , random_state=42 , stratify = y)

In [8]:
X_train.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'num_compromised', 'su_attempted', 'num_root',
       'num_file_creations', 'num_shells', 'num_access_files', 'count',
       'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
       'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate',
       'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'protocol_type_tcp',
       'protocol_type_udp', 'service_http', 'service_other', 'service_private',
       'service_smtp', 'flag_S0', 'flag_SF', 'flag_other', 'land_1',
       'logged_in_1', 'root_shell_1', 'is_host_login_1', 'is_guest_login_1'],
      dtype='object')

In [9]:
y_train.head(5)

114320    0
104096    1
68126     0
80449     0
30561     2
Name: attack_category, dtype: int64

<br/>
<br/>

#### REINDEXING DF

In [10]:
X_train = X_train.reset_index(drop = True)
y_train = y_train.reset_index(drop = True)

In [11]:
X_train

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
1     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
2     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
4     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
...         ...        ...        ...             ...       ...       ...   
88176 -0.110249  -0.007727  -0.004514       -0.089486 -0.007736 -0.095076   
88177 -0.110249  -0.007755  -0.004887       -0.089486 -0.007736 -0.095076   
88178 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
88179 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
88180 -0.110249  -0.007755  -0.004908       -0.089486 -0.007736 -0.095076   

       num_failed_logins  num_compromised  su_attempted  num_root  \
0              -0.027023        -0.011664     -0.024437 -0.012385   
1              -0.027023        -0.011664     -0.024437 -0.012385   
2              -0.027023        -0.011664     -0.024437 -0.012385   
3              -0.027023        -0.011664     -0.024437 -0.012385   
4              -0.027023        -0.011664     -0.024437 -0.012385   
...                  ...              ...           ...       ...   
88176          -0.027023        -0.011664     -0.024437 -0.012385   
88177          -0.027023        -0.011664     -0.024437 -0.012385   
88178          -0.027023        -0.011664     -0.024437 -0.012385   
88179          -0.027023        -0.011664     -0.024437 -0.012385   
88180          -0.027023        -0.011664     -0.024437 -0.012385   

       num_file_creations  num_shells  num_access_files     count  srv_count  \
0                -0.02618    -0.01861         -0.041221  1.806792  -0.078996   
1                -0.02618    -0.01861         -0.041221 -0.725778  -0.368110   
2                -0.02618    -0.01861         -0.041221  0.881094  -0.216669   
3                -0.02618    -0.01861         -0.041221  0.688968  -0.354343   
4                -0.02618    -0.01861         -0.041221 -0.367725  -0.257971   
...                   ...         ...               ...       ...        ...   
88176            -0.02618    -0.01861         -0.041221 -0.664647  -0.271739   
88177            -0.02618    -0.01861         -0.041221 -0.053337   1.793366   
88178            -0.02618    -0.01861         -0.041221  0.523041  -0.175367   
88179            -0.02618    -0.01861         -0.041221  1.370142  -0.326808   
88180            -0.02618    -0.01861         -0.041221  0.418245   2.536803   

       serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0         1.602664         1.605104    -0.374362        -0.374432   
1        -0.637209        -0.631929     2.746403         2.715365   
2         1.602664         1.605104    -0.374362        -0.374432   
3         1.602664         1.605104    -0.374362        -0.374432   
4        -0.637209        -0.631929    -0.374362        -0.374432   
...            ...              ...          ...              ...   
88176    -0.637209        -0.631929    -0.374362        -0.374432   
88177    -0.637209        -0.631929    -0.374362        -0.374432   
88178     1.602664         1.605104    -0.374362        -0.374432   
88179    -0.637209        -0.631929     2.746403         2.715365   
88180    -0.637209        -0.631929    -0.374362        -0.374432   

       same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0          -1.321428      -0.072389           -0.374560        0.734343   
1           0.771283      -0.349683           -0.374560       -1.725191   
2          -1.366922      -0.016930           -0.374560        0.734343   
3          -1.480656      -0.016930           -0.374560        0.734343   
4          -1.025719       0.204906           -0.374560        0.734343   
...          

In [10]:
y_train

0        0
1        1
2        0
3        0
4        2
        ..
88176    1
88177    1
88178    0
88179    0
88180    1
Name: attack_category, Length: 88181, dtype: int64

In [12]:
X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

In [12]:
X_test

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
1     -0.110249  -0.007707  -0.004843       -0.089486 -0.007736 -0.095076   
2     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
3     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
4     -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
...         ...        ...        ...             ...       ...       ...   
37787 -0.110249  -0.007741  -0.004919       -0.089486 -0.007736 -0.095076   
37788 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095076   
37789 -0.110249  -0.007709  -0.004393       -0.089486 -0.007736 -0.095076   
37790 -0.110249  -0.007722  -0.001621       -0.089486 -0.007736 -0.095076   
37791 -0.110249  -0.007478  -0.004837       -0.089486 -0.007736 -0.095076   

       num_failed_logins  num_compromised  su_attempted  num_root  \
0              -0.027023        -0.011664     -0.024437 -0.012385   
1              -0.027023        -0.011664     -0.024437 -0.012385   
2              -0.027023        -0.011664     -0.024437 -0.012385   
3              -0.027023        -0.011664     -0.024437 -0.012385   
4              -0.027023        -0.011664     -0.024437 -0.012385   
...                  ...              ...           ...       ...   
37787          -0.027023        -0.011664     -0.024437 -0.012385   
37788          -0.027023        -0.011664     -0.024437 -0.012385   
37789          -0.027023        -0.011664     -0.024437 -0.012385   
37790          -0.027023        -0.011664     -0.024437 -0.012385   
37791          -0.027023        -0.011664     -0.024437 -0.012385   

       num_file_creations  num_shells  num_access_files     count  srv_count  \
0                -0.02618    -0.01861         -0.041221 -0.437589  -0.368110   
1                -0.02618    -0.01861         -0.041221 -0.647181  -0.244204   
2                -0.02618    -0.01861         -0.041221 -0.725778  -0.368110   
3                -0.02618    -0.01861         -0.041221 -0.524919  -0.326808   
4                -0.02618    -0.01861         -0.041221 -0.088269  -0.368110   
...                   ...         ...               ...       ...        ...   
37787            -0.02618    -0.01861         -0.041221 -0.682113  -0.354343   
37788            -0.02618    -0.01861         -0.041221  1.745661  -0.134065   
37789            -0.02618    -0.01861         -0.041221 -0.647181  -0.230437   
37790            -0.02618    -0.01861         -0.041221 -0.708312  -0.340575   
37791            -0.02618    -0.01861         -0.041221 -0.725778  -0.368110   

       serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0        -0.637209        -0.631929     2.746403         2.715365   
1        -0.637209        -0.631929    -0.374362        -0.374432   
2        -0.637209        -0.631929     2.746403         2.715365   
3         1.602664         1.605104    -0.374362        -0.374432   
4        -0.614811        -0.631929     2.496742         2.715365   
...            ...              ...          ...              ...   
37787    -0.637209        -0.631929    -0.374362        -0.374432   
37788     1.602664         1.605104    -0.374362        -0.374432   
37789    -0.637209        -0.631929    -0.374362        -0.374432   
37790    -0.637209        -0.631929    -0.374362        -0.374432   
37791    -0.637209        -0.631929    -0.374362        -0.374432   

       same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0          -1.435162       2.589639           -0.374560        0.220260   
1           0.771283      -0.349683           -0.374560        0.734343   
2           0.771283      -0.349683           -0.374560       -1.160708   
3          -1.116706       0.315824           -0.374560        0.734343   
4          -1.480656       5.196208           -0.374560        0.734343   
...          

In [13]:
y_test

0        2
1        1
2        2
3        0
4        2
        ..
37787    1
37788    0
37789    1
37790    1
37791    1
Name: attack_category, Length: 37792, dtype: int64

<br/>
<br/>

### MODEL

In [13]:
from sklearn.linear_model import LogisticRegression

# multinomial set for softmax regression
model = LogisticRegression(solver='lbfgs', multi_class='multinomial')
model.fit(X_train, y_train)

D:\computer\Programming\python\python_download\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [14]:
y_pred = model.predict(X_test)
y_pred

array([2, 1, 2, ..., 1, 1, 1], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
y_true = y_test
target_names = [ 'dos', 'normal', 'probe' , 'r2l' , 'u2r' ]
report = classification_report(y_true, y_pred, target_names=target_names)

In [16]:
print(report)

              precision    recall  f1-score   support

         dos       0.99      0.98      0.98     13778
      normal       0.98      0.99      0.98     20479
       probe       0.97      0.95      0.96      3497
         r2l       0.94      0.64      0.76        25
         u2r       0.71      0.38      0.50        13

    accuracy                           0.98     37792
   macro avg       0.92      0.79      0.84     37792
weighted avg       0.98      0.98      0.98     37792



In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_true,y_pred)
print(confusion_matrix)

[[13447   323     8     0     0]
 [  157 20237    82     1     2]
 [   17   146  3334     0     0]
 [    0     9     0    16     0]
 [    0     8     0     0     5]]


In [18]:
pd.DataFrame(confusion_matrix , index = target_names , columns = target_names)

dos  normal  probe  r2l  u2r
dos     13447     323      8    0    0
normal    157   20237     82    1    2
probe      17     146   3334    0    0
r2l         0       9      0   16    0
u2r         0       8      0    0    5

In [19]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score 
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score( y_true , y_pred , average = None )
recall = recall_score( y_true , y_pred , average = None )
f1score = f1_score( y_true , y_pred , average = None )

In [20]:
print(accuracy)
print(precision)
print(recall)
print(f1score)

0.9800751481795089
[0.98722561 0.9765478  0.97371495 0.94117647 0.71428571]
[0.97597619 0.98818302 0.95338862 0.64       0.38461538]
[0.98156867 0.98233095 0.96344459 0.76190476 0.5       ]


In [50]:
data = {
    "model" : "Logistic Regression",
    "solver" : "lbfgs",
    "multiclass" : "multinomial",
    "accuracy" : accuracy ,
    "precision" : precision.tolist() ,
    "recall" : recall.tolist() ,
    "F1_score" : f1score.tolist() ,
    "class_names" : target_names
}

data

{'model': 'Logistic Regression',
 'solver': 'lbfgs',
 'multiclass': 'multinomial',
 'accuracy': 0.9800751481795089,
 'precision': [0.9872256075178034,
  0.9765477971336196,
  0.9737149532710281,
  0.9411764705882353,
  0.7142857142857143],
 'recall': [0.9759761939323559,
  0.9881830167488647,
  0.9533886188161281,
  0.64,
  0.38461538461538464],
 'F1_score': [0.9815686703894303,
  0.9823309548080189,
  0.9634445889322353,
  0.7619047619047621,
  0.5],
 'class_names': ['dos', 'normal', 'probe', 'r2l', 'u2r']}

In [51]:
import json
with open("../../model_performances/logistic_regression.json", "w") as outfile:
    json.dump(data, outfile)